const creativeImages = [
  {
    number: 1,
    name: "Arta Jens",
    twitter: "artajens",
    image: "/img/artajens.webp",
    position: [1, 1, -2],
  },
  {
    number: 2,
    name: "Fringz",
    twitter: "7Fringz",
    image: "/img/7Fringz.webp",
    position: [-3.5, 0, -1],
    description:
      "Fringz is a french artist who makes paintings and digital art. Based in Paris, he is known for his unique style. He is exposed from 01 to 07 July 24 in the Aristik Factory located Boulevard Haussmann in Paris.",
    gallery: [
      "/img/7Fringz/1.webp",
      "/img/7Fringz/2.webp",
      "/img/7Fringz/3.webp",
      "/img/7Fringz/4.webp",
      "/img/7Fringz/5.webp",
      "/img/7Fringz/6.webp",
      "/img/7Fringz/7.webp",
      "/img/7Fringz/8.webp",
    ],
  },
  {
    number: 3,
    name: "ISKREAM",
    twitter: "iskream5",
    image: "/img/iskream5.webp",
    position: [6, -3.5, -1],
  },
  {
    number: 4,
    name: "Baastart",
    twitter: "baastart_",
    image: "/img/baastart_.webp",
    position: [-6, 5, -2],
    description:
      "From France, Baastart is a 21 years old graphic designer. He aims to convey emotions and tell stories through his creations.",
  },
  {
    number: 5,
    name: "Jake Fried",
    twitter: "jakejfried",
    image: "/img/jakejfried.webp",
    position: [0.5, -4, 0],
    description:
      "Jake Fried is an American artist known for his detailed, hand-drawn animations. Originally a painter, he uses materials like white-out, coffee, and ink to create fast-paced, evolving narratives in his films. His unique style explores themes of time and transformation, making him a notable figure in contemporary art.",
  },
  {
    number: 6,
    name: "Jesperish",
    twitter: "Jesperish",
    image: "/img/Jesperish.webp",
    position: [7, 5, -2],
    scale: 1.3,
  },
  {
    number: 7,
    name: "Salu CV",
    twitter: "salu_cv",
    image: "/img/salu_cv.webp",
    position: [-6, -5, -1],
  },
  {
    number: 8,
    name: "SenssyLee",
    twitter: "senssylee",
    image: "/img/senssylee.webp",
    position: [0.5, 5, 0],
  },
  {
    number: 9,
    name: "Blank Embrace",
    twitter: "BlankEmbrace",
    image: "/img/blankembrace.webp",
    position: [-9, 0, -2],
    scale: 1.3,
  },
  {
    number: 10,
    name: "NearBound",
    twitter: "nearbound",
    image: "/img/nearbound.webp",
    position: [10.5, -2, 0],
  },
  {
    number: 11,
    name: "Soviet Soleri",
    twitter: "sovietsoleri",
    image: "/img/sovietsoleri.webp",
    position: [-10, 5, -1],
  },
  {
    number: 12,
    name: "T4C2",
    twitter: "teocomyn",
    image: "/img/teocomyn.webp",
    position: [6, 0.4, 0],
    scale: 0.8,
  },
];

export default creativeImages;
